### Get all products
GET http://localhost:3000/products

### Create a new product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Laptop ASUS X515",
  "description": "Laptop de uso general con 8GB RAM y SSD",
  "category": "Electronics",
  "price": 12999.99,
  "stock": 15
}