### Get all products
GET http://localhost:3000/products

### Get product by ID
GET http://localhost:3000/products/79fce6c4-d52e-11f0-89bf-58f1af9bf708

### Create a new product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Monitor Zowie",
  "description": "Full HD IPS display",
  "category": "electronics",
  "price": 3499.99,
  "stock": 8,
  "isActive": 0
}
### Get products by category
### ?category=Electronics
### ?category=Storage
### ?category=Accessories
### ?category=Furniture
GET http://localhost:3000/products?name=a&isActive=0

### Update product
PUT http://localhost:3000/products/79fce6c4-d52e-11f0-89bf-58f1af9bf708
Content-Type: application/json

{
  "name": "Monitor Asus rog strix",
  "description": "Full HD IPS display",
  "category": "electronics",
  "price": 3499.99,
  "stock": 8,
  "isDeleted": 0
}

### Update product status
PATCH http://localhost:3000/products/2580ab9c-96fa-4b7a-ad84-49ce25e6959a
Content-Type: application/json

{
  "isActive": 0
}

### Soft-Delete product
DELETE http://localhost:3000/products/79fce6c4-d52e-11f0-89bf-58f1af9bf708


### Inventory entry
POST http://localhost:3000/inventory/79fce6c4-d52e-11f0-89bf-58f1af9bf708/entry
Content-Type:  application/json

{
  "quantity": 200
}

### Inventory exit 
POST http://localhost:3000/inventory/79fce6c4-d52e-11f0-89bf-58f1af9bf708/exit
Content-Type:  application/json

{
  "quantity": 1000
}

### GET
GET http://localhost:3000/inventory/79fe5279-d52e-11f0-89bf-